services:
  - type: web
    name: api-laravel
    env: php
    region: oregon
    buildCommand: |
      composer install
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
envVars:
  - key: APP_KEY
    value: (tu app key)
  - key: DB_HOST
    fromDatabase:
      name: tu-base-de-datos
      property: host
